---
development:
  dialect: postgres
  database: hurtownia_development
  user: postgres
  password: Sharingan7
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:Sharingan7@127.0.0.1:5432/hurtownia_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:Sharingan7@127.0.0.1:5432/hurtownia_production?sslmode=disable"}}
