package actions

import (

  "fmt"
  "net/http"
  "github.com/gobuffalo/buffalo"
  "github.com/gobuffalo/pop"
  "github.com/gobuffalo/x/responder"
  "github.com/hurtownia/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Klienci)
// DB Table: Plural (kliencis)
// Resource: Plural (Kliencis)
// Path: Plural (/kliencis)
// View Template Folder: Plural (/templates/kliencis/)

// KliencisResource is the resource for the Klienci model
type KliencisResource struct{
  buffalo.Resource
}

// List gets all Kliencis. This function is mapped to the path
// GET /kliencis
func (v KliencisResource) List(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  kliencis := &models.Kliencis{}

  // Paginate results. Params "page" and "per_page" control pagination.
  // Default values are "page=1" and "per_page=20".
  q := tx.PaginateFromParams(c.Params())

  // Retrieve all Kliencis from the DB
  if err := q.All(kliencis); err != nil {
    return err
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // Add the paginator to the context so it can be used in the template.
    c.Set("pagination", q.Paginator)

    c.Set("kliencis", kliencis)
    return c.Render(http.StatusOK, r.HTML("/kliencis/index.plush.html"))
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(200, r.JSON(kliencis))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(200, r.XML(kliencis))
  }).Respond(c)
}

// Show gets the data for one Klienci. This function is mapped to
// the path GET /kliencis/{klienci_id}
func (v KliencisResource) Show(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Klienci
  klienci := &models.Klienci{}

  // To find the Klienci the parameter klienci_id is used.
  if err := tx.Find(klienci, c.Param("klienci_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    c.Set("klienci", klienci)

    return c.Render(http.StatusOK, r.HTML("/kliencis/show.plush.html"))
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(200, r.JSON(klienci))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(200, r.XML(klienci))
  }).Respond(c)
}

// New renders the form for creating a new Klienci.
// This function is mapped to the path GET /kliencis/new
func (v KliencisResource) New(c buffalo.Context) error {
  c.Set("klienci", &models.Klienci{})

  return c.Render(http.StatusOK, r.HTML("/kliencis/new.plush.html"))
}
// Create adds a Klienci to the DB. This function is mapped to the
// path POST /kliencis
func (v KliencisResource) Create(c buffalo.Context) error {
  // Allocate an empty Klienci
  klienci := &models.Klienci{}

  // Bind klienci to the html form elements
  if err := c.Bind(klienci); err != nil {
    return err
  }

  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Validate the data from the html form
  verrs, err := tx.ValidateAndCreate(klienci)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    return responder.Wants("html", func (c buffalo.Context) error {
      // Make the errors available inside the html template
      c.Set("errors", verrs)

      // Render again the new.html template that the user can
      // correct the input.
      c.Set("klienci", klienci)

      return c.Render(http.StatusUnprocessableEntity, r.HTML("/kliencis/new.plush.html"))
    }).Wants("json", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
    }).Wants("xml", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
    }).Respond(c)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a success message
    c.Flash().Add("success", T.Translate(c, "klienci.created.success"))

    // and redirect to the show page
    return c.Redirect(http.StatusSeeOther, "/kliencis/%v", klienci.ID)
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusCreated, r.JSON(klienci))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusCreated, r.XML(klienci))
  }).Respond(c)
}

// Edit renders a edit form for a Klienci. This function is
// mapped to the path GET /kliencis/{klienci_id}/edit
func (v KliencisResource) Edit(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Klienci
  klienci := &models.Klienci{}

  if err := tx.Find(klienci, c.Param("klienci_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  c.Set("klienci", klienci)
  return c.Render(http.StatusOK, r.HTML("/kliencis/edit.plush.html"))
}
// Update changes a Klienci in the DB. This function is mapped to
// the path PUT /kliencis/{klienci_id}
func (v KliencisResource) Update(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Klienci
  klienci := &models.Klienci{}

  if err := tx.Find(klienci, c.Param("klienci_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  // Bind Klienci to the html form elements
  if err := c.Bind(klienci); err != nil {
    return err
  }

  verrs, err := tx.ValidateAndUpdate(klienci)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    return responder.Wants("html", func (c buffalo.Context) error {
      // Make the errors available inside the html template
      c.Set("errors", verrs)

      // Render again the edit.html template that the user can
      // correct the input.
      c.Set("klienci", klienci)

      return c.Render(http.StatusUnprocessableEntity, r.HTML("/kliencis/edit.plush.html"))
    }).Wants("json", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
    }).Wants("xml", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
    }).Respond(c)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a success message
    c.Flash().Add("success", T.Translate(c, "klienci.updated.success"))

    // and redirect to the show page
    return c.Redirect(http.StatusSeeOther, "/kliencis/%v", klienci.ID)
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.JSON(klienci))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.XML(klienci))
  }).Respond(c)
}

// Destroy deletes a Klienci from the DB. This function is mapped
// to the path DELETE /kliencis/{klienci_id}
func (v KliencisResource) Destroy(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Klienci
  klienci := &models.Klienci{}

  // To find the Klienci the parameter klienci_id is used.
  if err := tx.Find(klienci, c.Param("klienci_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  if err := tx.Destroy(klienci); err != nil {
    return err
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a flash message
    c.Flash().Add("success", T.Translate(c, "klienci.destroyed.success"))

    // Redirect to the index page
    return c.Redirect(http.StatusSeeOther, "/kliencis")
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.JSON(klienci))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.XML(klienci))
  }).Respond(c)
}
