package actions

import (

  "fmt"
  "net/http"
  "github.com/gobuffalo/buffalo"
  "github.com/gobuffalo/pop"
  "github.com/gobuffalo/x/responder"
  "github.com/hurtownia/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Kontum)
// DB Table: Plural (konta)
// Resource: Plural (Konta)
// Path: Plural (/konta)
// View Template Folder: Plural (/templates/konta/)

// KontaResource is the resource for the Kontum model
type KontaResource struct{
  buffalo.Resource
}

// List gets all Konta. This function is mapped to the path
// GET /konta
func (v KontaResource) List(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  konta := &models.Konta{}

  // Paginate results. Params "page" and "per_page" control pagination.
  // Default values are "page=1" and "per_page=20".
  q := tx.PaginateFromParams(c.Params())

  // Retrieve all Konta from the DB
  if err := q.All(konta); err != nil {
    return err
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // Add the paginator to the context so it can be used in the template.
    c.Set("pagination", q.Paginator)

    c.Set("konta", konta)
    return c.Render(http.StatusOK, r.HTML("/konta/index.plush.html"))
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(200, r.JSON(konta))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(200, r.XML(konta))
  }).Respond(c)
}

// Show gets the data for one Kontum. This function is mapped to
// the path GET /konta/{kontum_id}
func (v KontaResource) Show(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Kontum
  kontum := &models.Kontum{}

  // To find the Kontum the parameter kontum_id is used.
  if err := tx.Find(kontum, c.Param("kontum_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    c.Set("kontum", kontum)

    return c.Render(http.StatusOK, r.HTML("/konta/show.plush.html"))
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(200, r.JSON(kontum))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(200, r.XML(kontum))
  }).Respond(c)
}

// New renders the form for creating a new Kontum.
// This function is mapped to the path GET /konta/new
func (v KontaResource) New(c buffalo.Context) error {
  c.Set("kontum", &models.Kontum{})

  return c.Render(http.StatusOK, r.HTML("/konta/new.plush.html"))
}
// Create adds a Kontum to the DB. This function is mapped to the
// path POST /konta
func (v KontaResource) Create(c buffalo.Context) error {
  // Allocate an empty Kontum
  kontum := &models.Kontum{}

  // Bind kontum to the html form elements
  if err := c.Bind(kontum); err != nil {
    return err
  }

  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Validate the data from the html form
  verrs, err := tx.ValidateAndCreate(kontum)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    return responder.Wants("html", func (c buffalo.Context) error {
      // Make the errors available inside the html template
      c.Set("errors", verrs)

      // Render again the new.html template that the user can
      // correct the input.
      c.Set("kontum", kontum)

      return c.Render(http.StatusUnprocessableEntity, r.HTML("/konta/new.plush.html"))
    }).Wants("json", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
    }).Wants("xml", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
    }).Respond(c)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a success message
    c.Flash().Add("success", T.Translate(c, "kontum.created.success"))

    // and redirect to the show page
    return c.Redirect(http.StatusSeeOther, "/konta/%v", kontum.ID)
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusCreated, r.JSON(kontum))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusCreated, r.XML(kontum))
  }).Respond(c)
}

// Edit renders a edit form for a Kontum. This function is
// mapped to the path GET /konta/{kontum_id}/edit
func (v KontaResource) Edit(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Kontum
  kontum := &models.Kontum{}

  if err := tx.Find(kontum, c.Param("kontum_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  c.Set("kontum", kontum)
  return c.Render(http.StatusOK, r.HTML("/konta/edit.plush.html"))
}
// Update changes a Kontum in the DB. This function is mapped to
// the path PUT /konta/{kontum_id}
func (v KontaResource) Update(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Kontum
  kontum := &models.Kontum{}

  if err := tx.Find(kontum, c.Param("kontum_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  // Bind Kontum to the html form elements
  if err := c.Bind(kontum); err != nil {
    return err
  }

  verrs, err := tx.ValidateAndUpdate(kontum)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    return responder.Wants("html", func (c buffalo.Context) error {
      // Make the errors available inside the html template
      c.Set("errors", verrs)

      // Render again the edit.html template that the user can
      // correct the input.
      c.Set("kontum", kontum)

      return c.Render(http.StatusUnprocessableEntity, r.HTML("/konta/edit.plush.html"))
    }).Wants("json", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
    }).Wants("xml", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
    }).Respond(c)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a success message
    c.Flash().Add("success", T.Translate(c, "kontum.updated.success"))

    // and redirect to the show page
    return c.Redirect(http.StatusSeeOther, "/konta/%v", kontum.ID)
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.JSON(kontum))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.XML(kontum))
  }).Respond(c)
}

// Destroy deletes a Kontum from the DB. This function is mapped
// to the path DELETE /konta/{kontum_id}
func (v KontaResource) Destroy(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Kontum
  kontum := &models.Kontum{}

  // To find the Kontum the parameter kontum_id is used.
  if err := tx.Find(kontum, c.Param("kontum_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  if err := tx.Destroy(kontum); err != nil {
    return err
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a flash message
    c.Flash().Add("success", T.Translate(c, "kontum.destroyed.success"))

    // Redirect to the index page
    return c.Redirect(http.StatusSeeOther, "/konta")
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.JSON(kontum))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.XML(kontum))
  }).Respond(c)
}
