package actions

import (

  "fmt"
  "net/http"
  "github.com/gobuffalo/buffalo"
  "github.com/gobuffalo/pop"
  "github.com/gobuffalo/x/responder"
  "github.com/hurtownia/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Platnosci)
// DB Table: Plural (platnoscis)
// Resource: Plural (Platnoscis)
// Path: Plural (/platnoscis)
// View Template Folder: Plural (/templates/platnoscis/)

// PlatnoscisResource is the resource for the Platnosci model
type PlatnoscisResource struct{
  buffalo.Resource
}

// List gets all Platnoscis. This function is mapped to the path
// GET /platnoscis
func (v PlatnoscisResource) List(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  platnoscis := &models.Platnoscis{}

  // Paginate results. Params "page" and "per_page" control pagination.
  // Default values are "page=1" and "per_page=20".
  q := tx.PaginateFromParams(c.Params())

  // Retrieve all Platnoscis from the DB
  if err := q.All(platnoscis); err != nil {
    return err
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // Add the paginator to the context so it can be used in the template.
    c.Set("pagination", q.Paginator)

    c.Set("platnoscis", platnoscis)
    return c.Render(http.StatusOK, r.HTML("/platnoscis/index.plush.html"))
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(200, r.JSON(platnoscis))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(200, r.XML(platnoscis))
  }).Respond(c)
}

// Show gets the data for one Platnosci. This function is mapped to
// the path GET /platnoscis/{platnosci_id}
func (v PlatnoscisResource) Show(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Platnosci
  platnosci := &models.Platnosci{}

  // To find the Platnosci the parameter platnosci_id is used.
  if err := tx.Find(platnosci, c.Param("platnosci_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    c.Set("platnosci", platnosci)

    return c.Render(http.StatusOK, r.HTML("/platnoscis/show.plush.html"))
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(200, r.JSON(platnosci))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(200, r.XML(platnosci))
  }).Respond(c)
}

// New renders the form for creating a new Platnosci.
// This function is mapped to the path GET /platnoscis/new
func (v PlatnoscisResource) New(c buffalo.Context) error {
  c.Set("platnosci", &models.Platnosci{})

  return c.Render(http.StatusOK, r.HTML("/platnoscis/new.plush.html"))
}
// Create adds a Platnosci to the DB. This function is mapped to the
// path POST /platnoscis
func (v PlatnoscisResource) Create(c buffalo.Context) error {
  // Allocate an empty Platnosci
  platnosci := &models.Platnosci{}

  // Bind platnosci to the html form elements
  if err := c.Bind(platnosci); err != nil {
    return err
  }

  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Validate the data from the html form
  verrs, err := tx.ValidateAndCreate(platnosci)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    return responder.Wants("html", func (c buffalo.Context) error {
      // Make the errors available inside the html template
      c.Set("errors", verrs)

      // Render again the new.html template that the user can
      // correct the input.
      c.Set("platnosci", platnosci)

      return c.Render(http.StatusUnprocessableEntity, r.HTML("/platnoscis/new.plush.html"))
    }).Wants("json", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
    }).Wants("xml", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
    }).Respond(c)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a success message
    c.Flash().Add("success", T.Translate(c, "platnosci.created.success"))

    // and redirect to the show page
    return c.Redirect(http.StatusSeeOther, "/platnoscis/%v", platnosci.ID)
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusCreated, r.JSON(platnosci))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusCreated, r.XML(platnosci))
  }).Respond(c)
}

// Edit renders a edit form for a Platnosci. This function is
// mapped to the path GET /platnoscis/{platnosci_id}/edit
func (v PlatnoscisResource) Edit(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Platnosci
  platnosci := &models.Platnosci{}

  if err := tx.Find(platnosci, c.Param("platnosci_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  c.Set("platnosci", platnosci)
  return c.Render(http.StatusOK, r.HTML("/platnoscis/edit.plush.html"))
}
// Update changes a Platnosci in the DB. This function is mapped to
// the path PUT /platnoscis/{platnosci_id}
func (v PlatnoscisResource) Update(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Platnosci
  platnosci := &models.Platnosci{}

  if err := tx.Find(platnosci, c.Param("platnosci_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  // Bind Platnosci to the html form elements
  if err := c.Bind(platnosci); err != nil {
    return err
  }

  verrs, err := tx.ValidateAndUpdate(platnosci)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    return responder.Wants("html", func (c buffalo.Context) error {
      // Make the errors available inside the html template
      c.Set("errors", verrs)

      // Render again the edit.html template that the user can
      // correct the input.
      c.Set("platnosci", platnosci)

      return c.Render(http.StatusUnprocessableEntity, r.HTML("/platnoscis/edit.plush.html"))
    }).Wants("json", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
    }).Wants("xml", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
    }).Respond(c)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a success message
    c.Flash().Add("success", T.Translate(c, "platnosci.updated.success"))

    // and redirect to the show page
    return c.Redirect(http.StatusSeeOther, "/platnoscis/%v", platnosci.ID)
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.JSON(platnosci))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.XML(platnosci))
  }).Respond(c)
}

// Destroy deletes a Platnosci from the DB. This function is mapped
// to the path DELETE /platnoscis/{platnosci_id}
func (v PlatnoscisResource) Destroy(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Platnosci
  platnosci := &models.Platnosci{}

  // To find the Platnosci the parameter platnosci_id is used.
  if err := tx.Find(platnosci, c.Param("platnosci_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  if err := tx.Destroy(platnosci); err != nil {
    return err
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a flash message
    c.Flash().Add("success", T.Translate(c, "platnosci.destroyed.success"))

    // Redirect to the index page
    return c.Redirect(http.StatusSeeOther, "/platnoscis")
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.JSON(platnosci))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.XML(platnosci))
  }).Respond(c)
}
