package actions

import (

  "fmt"
  "net/http"
  "github.com/gobuffalo/buffalo"
  "github.com/gobuffalo/pop"
  "github.com/gobuffalo/x/responder"
  "github.com/hurtownia/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Pozycje)
// DB Table: Plural (pozycjes)
// Resource: Plural (Pozycjes)
// Path: Plural (/pozycjes)
// View Template Folder: Plural (/templates/pozycjes/)

// PozycjesResource is the resource for the Pozycje model
type PozycjesResource struct{
  buffalo.Resource
}

// List gets all Pozycjes. This function is mapped to the path
// GET /pozycjes
func (v PozycjesResource) List(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  pozycjes := &models.Pozycjes{}

  // Paginate results. Params "page" and "per_page" control pagination.
  // Default values are "page=1" and "per_page=20".
  q := tx.PaginateFromParams(c.Params())

  // Retrieve all Pozycjes from the DB
  if err := q.All(pozycjes); err != nil {
    return err
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // Add the paginator to the context so it can be used in the template.
    c.Set("pagination", q.Paginator)

    c.Set("pozycjes", pozycjes)
    return c.Render(http.StatusOK, r.HTML("/pozycjes/index.plush.html"))
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(200, r.JSON(pozycjes))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(200, r.XML(pozycjes))
  }).Respond(c)
}

// Show gets the data for one Pozycje. This function is mapped to
// the path GET /pozycjes/{pozycje_id}
func (v PozycjesResource) Show(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Pozycje
  pozycje := &models.Pozycje{}

  // To find the Pozycje the parameter pozycje_id is used.
  if err := tx.Find(pozycje, c.Param("pozycje_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    c.Set("pozycje", pozycje)

    return c.Render(http.StatusOK, r.HTML("/pozycjes/show.plush.html"))
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(200, r.JSON(pozycje))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(200, r.XML(pozycje))
  }).Respond(c)
}

// New renders the form for creating a new Pozycje.
// This function is mapped to the path GET /pozycjes/new
func (v PozycjesResource) New(c buffalo.Context) error {
  c.Set("pozycje", &models.Pozycje{})

  return c.Render(http.StatusOK, r.HTML("/pozycjes/new.plush.html"))
}
// Create adds a Pozycje to the DB. This function is mapped to the
// path POST /pozycjes
func (v PozycjesResource) Create(c buffalo.Context) error {
  // Allocate an empty Pozycje
  pozycje := &models.Pozycje{}

  // Bind pozycje to the html form elements
  if err := c.Bind(pozycje); err != nil {
    return err
  }

  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Validate the data from the html form
  verrs, err := tx.ValidateAndCreate(pozycje)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    return responder.Wants("html", func (c buffalo.Context) error {
      // Make the errors available inside the html template
      c.Set("errors", verrs)

      // Render again the new.html template that the user can
      // correct the input.
      c.Set("pozycje", pozycje)

      return c.Render(http.StatusUnprocessableEntity, r.HTML("/pozycjes/new.plush.html"))
    }).Wants("json", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
    }).Wants("xml", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
    }).Respond(c)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a success message
    c.Flash().Add("success", T.Translate(c, "pozycje.created.success"))

    // and redirect to the show page
    return c.Redirect(http.StatusSeeOther, "/pozycjes/%v", pozycje.ID)
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusCreated, r.JSON(pozycje))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusCreated, r.XML(pozycje))
  }).Respond(c)
}

// Edit renders a edit form for a Pozycje. This function is
// mapped to the path GET /pozycjes/{pozycje_id}/edit
func (v PozycjesResource) Edit(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Pozycje
  pozycje := &models.Pozycje{}

  if err := tx.Find(pozycje, c.Param("pozycje_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  c.Set("pozycje", pozycje)
  return c.Render(http.StatusOK, r.HTML("/pozycjes/edit.plush.html"))
}
// Update changes a Pozycje in the DB. This function is mapped to
// the path PUT /pozycjes/{pozycje_id}
func (v PozycjesResource) Update(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Pozycje
  pozycje := &models.Pozycje{}

  if err := tx.Find(pozycje, c.Param("pozycje_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  // Bind Pozycje to the html form elements
  if err := c.Bind(pozycje); err != nil {
    return err
  }

  verrs, err := tx.ValidateAndUpdate(pozycje)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    return responder.Wants("html", func (c buffalo.Context) error {
      // Make the errors available inside the html template
      c.Set("errors", verrs)

      // Render again the edit.html template that the user can
      // correct the input.
      c.Set("pozycje", pozycje)

      return c.Render(http.StatusUnprocessableEntity, r.HTML("/pozycjes/edit.plush.html"))
    }).Wants("json", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
    }).Wants("xml", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
    }).Respond(c)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a success message
    c.Flash().Add("success", T.Translate(c, "pozycje.updated.success"))

    // and redirect to the show page
    return c.Redirect(http.StatusSeeOther, "/pozycjes/%v", pozycje.ID)
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.JSON(pozycje))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.XML(pozycje))
  }).Respond(c)
}

// Destroy deletes a Pozycje from the DB. This function is mapped
// to the path DELETE /pozycjes/{pozycje_id}
func (v PozycjesResource) Destroy(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Pozycje
  pozycje := &models.Pozycje{}

  // To find the Pozycje the parameter pozycje_id is used.
  if err := tx.Find(pozycje, c.Param("pozycje_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  if err := tx.Destroy(pozycje); err != nil {
    return err
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a flash message
    c.Flash().Add("success", T.Translate(c, "pozycje.destroyed.success"))

    // Redirect to the index page
    return c.Redirect(http.StatusSeeOther, "/pozycjes")
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.JSON(pozycje))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.XML(pozycje))
  }).Respond(c)
}
