package actions

import (

  "fmt"
  "net/http"
  "github.com/gobuffalo/buffalo"
  "github.com/gobuffalo/pop"
  "github.com/gobuffalo/x/responder"
  "github.com/hurtownia/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Produkty)
// DB Table: Plural (produkties)
// Resource: Plural (Produkties)
// Path: Plural (/produkties)
// View Template Folder: Plural (/templates/produkties/)

// ProduktiesResource is the resource for the Produkty model
type ProduktiesResource struct{
  buffalo.Resource
}

// List gets all Produkties. This function is mapped to the path
// GET /produkties
func (v ProduktiesResource) List(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  produkties := &models.Produkties{}

  // Paginate results. Params "page" and "per_page" control pagination.
  // Default values are "page=1" and "per_page=20".
  q := tx.PaginateFromParams(c.Params())

  // Retrieve all Produkties from the DB
  if err := q.All(produkties); err != nil {
    return err
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // Add the paginator to the context so it can be used in the template.
    c.Set("pagination", q.Paginator)

    c.Set("produkties", produkties)
    return c.Render(http.StatusOK, r.HTML("/produkties/index.plush.html"))
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(200, r.JSON(produkties))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(200, r.XML(produkties))
  }).Respond(c)
}

// Show gets the data for one Produkty. This function is mapped to
// the path GET /produkties/{produkty_id}
func (v ProduktiesResource) Show(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Produkty
  produkty := &models.Produkty{}

  // To find the Produkty the parameter produkty_id is used.
  if err := tx.Find(produkty, c.Param("produkty_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    c.Set("produkty", produkty)

    return c.Render(http.StatusOK, r.HTML("/produkties/show.plush.html"))
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(200, r.JSON(produkty))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(200, r.XML(produkty))
  }).Respond(c)
}

// New renders the form for creating a new Produkty.
// This function is mapped to the path GET /produkties/new
func (v ProduktiesResource) New(c buffalo.Context) error {
  c.Set("produkty", &models.Produkty{})

  return c.Render(http.StatusOK, r.HTML("/produkties/new.plush.html"))
}
// Create adds a Produkty to the DB. This function is mapped to the
// path POST /produkties
func (v ProduktiesResource) Create(c buffalo.Context) error {
  // Allocate an empty Produkty
  produkty := &models.Produkty{}

  // Bind produkty to the html form elements
  if err := c.Bind(produkty); err != nil {
    return err
  }

  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Validate the data from the html form
  verrs, err := tx.ValidateAndCreate(produkty)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    return responder.Wants("html", func (c buffalo.Context) error {
      // Make the errors available inside the html template
      c.Set("errors", verrs)

      // Render again the new.html template that the user can
      // correct the input.
      c.Set("produkty", produkty)

      return c.Render(http.StatusUnprocessableEntity, r.HTML("/produkties/new.plush.html"))
    }).Wants("json", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
    }).Wants("xml", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
    }).Respond(c)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a success message
    c.Flash().Add("success", T.Translate(c, "produkty.created.success"))

    // and redirect to the show page
    return c.Redirect(http.StatusSeeOther, "/produkties/%v", produkty.ID)
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusCreated, r.JSON(produkty))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusCreated, r.XML(produkty))
  }).Respond(c)
}

// Edit renders a edit form for a Produkty. This function is
// mapped to the path GET /produkties/{produkty_id}/edit
func (v ProduktiesResource) Edit(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Produkty
  produkty := &models.Produkty{}

  if err := tx.Find(produkty, c.Param("produkty_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  c.Set("produkty", produkty)
  return c.Render(http.StatusOK, r.HTML("/produkties/edit.plush.html"))
}
// Update changes a Produkty in the DB. This function is mapped to
// the path PUT /produkties/{produkty_id}
func (v ProduktiesResource) Update(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Produkty
  produkty := &models.Produkty{}

  if err := tx.Find(produkty, c.Param("produkty_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  // Bind Produkty to the html form elements
  if err := c.Bind(produkty); err != nil {
    return err
  }

  verrs, err := tx.ValidateAndUpdate(produkty)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    return responder.Wants("html", func (c buffalo.Context) error {
      // Make the errors available inside the html template
      c.Set("errors", verrs)

      // Render again the edit.html template that the user can
      // correct the input.
      c.Set("produkty", produkty)

      return c.Render(http.StatusUnprocessableEntity, r.HTML("/produkties/edit.plush.html"))
    }).Wants("json", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
    }).Wants("xml", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
    }).Respond(c)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a success message
    c.Flash().Add("success", T.Translate(c, "produkty.updated.success"))

    // and redirect to the show page
    return c.Redirect(http.StatusSeeOther, "/produkties/%v", produkty.ID)
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.JSON(produkty))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.XML(produkty))
  }).Respond(c)
}

// Destroy deletes a Produkty from the DB. This function is mapped
// to the path DELETE /produkties/{produkty_id}
func (v ProduktiesResource) Destroy(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Produkty
  produkty := &models.Produkty{}

  // To find the Produkty the parameter produkty_id is used.
  if err := tx.Find(produkty, c.Param("produkty_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  if err := tx.Destroy(produkty); err != nil {
    return err
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a flash message
    c.Flash().Add("success", T.Translate(c, "produkty.destroyed.success"))

    // Redirect to the index page
    return c.Redirect(http.StatusSeeOther, "/produkties")
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.JSON(produkty))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.XML(produkty))
  }).Respond(c)
}
