package actions

import (

  "fmt"
  "net/http"
  "github.com/gobuffalo/buffalo"
  "github.com/gobuffalo/pop"
  "github.com/gobuffalo/x/responder"
  "github.com/hurtownia/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Sprzedawcy)
// DB Table: Plural (sprzedawcies)
// Resource: Plural (Sprzedawcies)
// Path: Plural (/sprzedawcies)
// View Template Folder: Plural (/templates/sprzedawcies/)

// SprzedawciesResource is the resource for the Sprzedawcy model
type SprzedawciesResource struct{
  buffalo.Resource
}

// List gets all Sprzedawcies. This function is mapped to the path
// GET /sprzedawcies
func (v SprzedawciesResource) List(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  sprzedawcies := &models.Sprzedawcies{}

  // Paginate results. Params "page" and "per_page" control pagination.
  // Default values are "page=1" and "per_page=20".
  q := tx.PaginateFromParams(c.Params())

  // Retrieve all Sprzedawcies from the DB
  if err := q.All(sprzedawcies); err != nil {
    return err
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // Add the paginator to the context so it can be used in the template.
    c.Set("pagination", q.Paginator)

    c.Set("sprzedawcies", sprzedawcies)
    return c.Render(http.StatusOK, r.HTML("/sprzedawcies/index.plush.html"))
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(200, r.JSON(sprzedawcies))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(200, r.XML(sprzedawcies))
  }).Respond(c)
}

// Show gets the data for one Sprzedawcy. This function is mapped to
// the path GET /sprzedawcies/{sprzedawcy_id}
func (v SprzedawciesResource) Show(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Sprzedawcy
  sprzedawcy := &models.Sprzedawcy{}

  // To find the Sprzedawcy the parameter sprzedawcy_id is used.
  if err := tx.Find(sprzedawcy, c.Param("sprzedawcy_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    c.Set("sprzedawcy", sprzedawcy)

    return c.Render(http.StatusOK, r.HTML("/sprzedawcies/show.plush.html"))
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(200, r.JSON(sprzedawcy))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(200, r.XML(sprzedawcy))
  }).Respond(c)
}

// New renders the form for creating a new Sprzedawcy.
// This function is mapped to the path GET /sprzedawcies/new
func (v SprzedawciesResource) New(c buffalo.Context) error {
  c.Set("sprzedawcy", &models.Sprzedawcy{})

  return c.Render(http.StatusOK, r.HTML("/sprzedawcies/new.plush.html"))
}
// Create adds a Sprzedawcy to the DB. This function is mapped to the
// path POST /sprzedawcies
func (v SprzedawciesResource) Create(c buffalo.Context) error {
  // Allocate an empty Sprzedawcy
  sprzedawcy := &models.Sprzedawcy{}

  // Bind sprzedawcy to the html form elements
  if err := c.Bind(sprzedawcy); err != nil {
    return err
  }

  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Validate the data from the html form
  verrs, err := tx.ValidateAndCreate(sprzedawcy)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    return responder.Wants("html", func (c buffalo.Context) error {
      // Make the errors available inside the html template
      c.Set("errors", verrs)

      // Render again the new.html template that the user can
      // correct the input.
      c.Set("sprzedawcy", sprzedawcy)

      return c.Render(http.StatusUnprocessableEntity, r.HTML("/sprzedawcies/new.plush.html"))
    }).Wants("json", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
    }).Wants("xml", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
    }).Respond(c)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a success message
    c.Flash().Add("success", T.Translate(c, "sprzedawcy.created.success"))

    // and redirect to the show page
    return c.Redirect(http.StatusSeeOther, "/sprzedawcies/%v", sprzedawcy.ID)
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusCreated, r.JSON(sprzedawcy))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusCreated, r.XML(sprzedawcy))
  }).Respond(c)
}

// Edit renders a edit form for a Sprzedawcy. This function is
// mapped to the path GET /sprzedawcies/{sprzedawcy_id}/edit
func (v SprzedawciesResource) Edit(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Sprzedawcy
  sprzedawcy := &models.Sprzedawcy{}

  if err := tx.Find(sprzedawcy, c.Param("sprzedawcy_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  c.Set("sprzedawcy", sprzedawcy)
  return c.Render(http.StatusOK, r.HTML("/sprzedawcies/edit.plush.html"))
}
// Update changes a Sprzedawcy in the DB. This function is mapped to
// the path PUT /sprzedawcies/{sprzedawcy_id}
func (v SprzedawciesResource) Update(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Sprzedawcy
  sprzedawcy := &models.Sprzedawcy{}

  if err := tx.Find(sprzedawcy, c.Param("sprzedawcy_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  // Bind Sprzedawcy to the html form elements
  if err := c.Bind(sprzedawcy); err != nil {
    return err
  }

  verrs, err := tx.ValidateAndUpdate(sprzedawcy)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    return responder.Wants("html", func (c buffalo.Context) error {
      // Make the errors available inside the html template
      c.Set("errors", verrs)

      // Render again the edit.html template that the user can
      // correct the input.
      c.Set("sprzedawcy", sprzedawcy)

      return c.Render(http.StatusUnprocessableEntity, r.HTML("/sprzedawcies/edit.plush.html"))
    }).Wants("json", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
    }).Wants("xml", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
    }).Respond(c)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a success message
    c.Flash().Add("success", T.Translate(c, "sprzedawcy.updated.success"))

    // and redirect to the show page
    return c.Redirect(http.StatusSeeOther, "/sprzedawcies/%v", sprzedawcy.ID)
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.JSON(sprzedawcy))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.XML(sprzedawcy))
  }).Respond(c)
}

// Destroy deletes a Sprzedawcy from the DB. This function is mapped
// to the path DELETE /sprzedawcies/{sprzedawcy_id}
func (v SprzedawciesResource) Destroy(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Sprzedawcy
  sprzedawcy := &models.Sprzedawcy{}

  // To find the Sprzedawcy the parameter sprzedawcy_id is used.
  if err := tx.Find(sprzedawcy, c.Param("sprzedawcy_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  if err := tx.Destroy(sprzedawcy); err != nil {
    return err
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a flash message
    c.Flash().Add("success", T.Translate(c, "sprzedawcy.destroyed.success"))

    // Redirect to the index page
    return c.Redirect(http.StatusSeeOther, "/sprzedawcies")
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.JSON(sprzedawcy))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.XML(sprzedawcy))
  }).Respond(c)
}
